src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AddressRepository::class)
 */
class Address
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ligne_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ligne_2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ligne_3;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    public function getId(): ?int
    {
        return $this->id;
    }

     public function __toString()
    {
        return $this->ligne_1; 
    }

    public function getLigne1(): ?string
    {
        return $this->ligne_1;
    }

    public function setLigne1(string $ligne_1): self
    {
        $this->ligne_1 = $ligne_1;

        return $this;
    }

    public function getLigne2(): ?string
    {
        return $this->ligne_2;
    }

    public function setLigne2(?string $ligne_2): self
    {
        $this->ligne_2 = $ligne_2;

        return $this;
    }

    public function getLigne3(): ?string
    {
        return $this->ligne_3;
    }

    public function setLigne3(?string $ligne_3): self
    {
        $this->ligne_3 = $ligne_3;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }
}

src/Form/AddressType.php
<?php

namespace App\Form;

use App\Entity\Address;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddressType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('ligne_1')
            ->add('ligne_2')
            ->add('ligne_3')
            ->add('postalCode')
            ->add('city')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Address::class,
        ]);
    }
}

src/Controller/AddressController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Form\AddressType;
use App\Repository\AddressRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/address")
 */
class AddressController extends AbstractController
{
    /**
     * @Route("/", name="address_index", methods={"GET"})
     */
    public function index(AddressRepository $addressRepository): Response
    {
        return $this->render('address/index.html.twig', [
            'addresses' => $addressRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="address_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $address = new Address();
        $form = $this->createForm(AddressType::class, $address);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($address);
            $entityManager->flush();

            return $this->redirectToRoute('address_index');
        }

        return $this->render('address/new.html.twig', [
            'address' => $address,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="address_show", methods={"GET"})
     */
    public function show(Address $address): Response
    {
        return $this->render('address/show.html.twig', [
            'address' => $address,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="address_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Address $address): Response
    {
        $form = $this->createForm(AddressType::class, $address);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('address_index');
        }

        return $this->render('address/edit.html.twig', [
            'address' => $address,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="address_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Address $address): Response
    {
        if ($this->isCsrfTokenValid('delete'.$address->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($address);
            $entityManager->flush();
        }

        return $this->redirectToRoute('address_index');
    }
}

templates/address/_delete_form.html.twig
<form method="post" action="{{ path('address_delete', {'id': address.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ address.id) }}">
    <button class="btn">Delete</button>
</form>

templates/address/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/address/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Address{% endblock %}

{% block body %}
    <h1>Edit Address</h1>

    {{ include('address/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('address_index') }}">back to list</a>

    {{ include('address/_delete_form.html.twig') }}
{% endblock %}

templates/address/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Address index{% endblock %}

{% block body %}
    <h1>Address index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ligne_1</th>
                <th>Ligne_2</th>
                <th>Ligne_3</th>
                <th>PostalCode</th>
                <th>City</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for address in addresses %}
            <tr>
                <td>{{ address.id }}</td>
                <td>{{ address.ligne1 }}</td>
                <td>{{ address.ligne2 }}</td>
                <td>{{ address.ligne3 }}</td>
                <td>{{ address.postalCode }}</td>
                <td>{{ address.city }}</td>
                <td>
                    <a href="{{ path('address_show', {'id': address.id}) }}">show</a>
                    <a href="{{ path('address_edit', {'id': address.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('address_new') }}">Create new</a>
{% endblock %}

templates/address/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Address{% endblock %}

{% block body %}
    <h1>Create new Address</h1>

    {{ include('address/_form.html.twig') }}

    <a href="{{ path('address_index') }}">back to list</a>
{% endblock %}

templates/address/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Address{% endblock %}

{% block body %}
    <h1>Address</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ address.id }}</td>
            </tr>
            <tr>
                <th>Ligne_1</th>
                <td>{{ address.ligne1 }}</td>
            </tr>
            <tr>
                <th>Ligne_2</th>
                <td>{{ address.ligne2 }}</td>
            </tr>
            <tr>
                <th>Ligne_3</th>
                <td>{{ address.ligne3 }}</td>
            </tr>
            <tr>
                <th>PostalCode</th>
                <td>{{ address.postalCode }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ address.city }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('address_index') }}">back to list</a>

    <a href="{{ path('address_edit', {'id': address.id}) }}">edit</a>

    {{ include('address/_delete_form.html.twig') }}
{% endblock %}